Site/Controllers/Order1Controller.cs
using Site.Entity;
using Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site.Controllers
{
    public class Order1Controller : Controller
    {
        DataContext db = new DataContext();
        // GET: Order1
        public ActionResult Index()
        {
            if (Session["Yetki"].ToString() == "Y" || Session["Yetki"].ToString() == "K")
            {

            }
            else
            {
                return RedirectToAction("PageError", "Error");
            }
            var order1s = db.Order1s.Select(i => new AdminOrder1()
            {
                Id = i.Id,
                OrderNumber = i.OrderNumber,
                OrderDate = i.OrderDate,
                OrderState = i.OrderState,
                Total = i.Total,
                Count = i.OrderLines1.Count
            }).OrderByDescending(i => i.OrderDate).ToList();
            return View(order1s);
        }
        public ActionResult Details(int id)
        {
            if (Session["Yetki"].ToString() == "Y" )
            {

            }
            else
            {
                return RedirectToAction("PageError", "Error");
            }
            var model = db.Order1s.Where(i => i.Id == id).Select(i => new OrderDetails1()
            {
                OrderId = i.Id,
                OrderNumber = i.OrderNumber,
                Total = i.Total,
                UserName = i.UserName,
                OrderDate = i.OrderDate,
                OrderState = i.OrderState,

                Adres = i.Adres,
                Sehir = i.Sehir,
                Semt = i.Semt,
                Mahalle = i.Mahalle,
                PostaKodu = i.PostaKodu,
               OrderLines1 = i.OrderLines1.Select(x => new OrderLineModel1()
                {
                    ProductId = x.ProductId,
                    RESIM = x.Product.RESIM,
                    ProductName = x.Product.OAD,
                    Quantity = x.Quantity,
                    FIYAT = x.Product.TOPLAM

                }).ToList()
            }).FirstOrDefault();

            return View(model);
        }
        public ActionResult UpdateOrderState(int OrderId, OrderState orderState)
        {
            var order1 = db.Order1s.FirstOrDefault(i => i.Id == OrderId);
            if (order1 != null)
            {
                order1.OrderState = orderState;
                db.SaveChanges();
                TempData["mesaj"] = "Bilgiler Kaydedildi";

                return RedirectToAction("Details", new { id = OrderId });
            }
            return RedirectToAction("Index");
        }
        public ActionResult BekleyenKiralamalar()
        {
            if (Session["Yetki"].ToString() == "Y" || Session["Yetki"].ToString() == "K")
            {

            }
            else
            {
                return RedirectToAction("PageError", "Error");
            }
            var model = db.Order1s.Where(i => i.OrderState == OrderState.Bekleniyor).ToList();
            return View(model);
        }
        public ActionResult KargolananKiralamalar()
        {
            if (Session["Yetki"].ToString() == "Y" || Session["Yetki"].ToString() == "K")
            {

            }
            else
            {
                return RedirectToAction("PageError", "Error");
            }
            var orders = db.Order1s.Where(i => i.OrderState == OrderState.Kargolandı).ToList();
            return View(orders);
        }
        public ActionResult TamamlananKiralamalar()
        {
            if (Session["Yetki"].ToString() == "Y" || Session["Yetki"].ToString() == "K")
            {

            }
            else
            {
                return RedirectToAction("PageError", "Error");
            }
            var orders = db.Order1s.Where(i => i.OrderState == OrderState.Tamamlandı).ToList();
            return View(orders);
        }
        public ActionResult PaketlenenKiralamalar()
        {
            if (Session["Yetki"].ToString() == "Y" || Session["Yetki"].ToString() == "K")
            {

            }
            else
            {
                return RedirectToAction("PageError", "Error");
            }
            var orders = db.Order1s.Where(i => i.OrderState == OrderState.Paketlendi).ToList();
            return View(orders);
        }
    }
}

Site/Views/Order1/BekleyenKiralamalar.cshtml
@using Site.Entity
@model IEnumerable<order1>
@{
    ViewBag.Title = "BekleyenKiralamalar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">

        <!-- /.box -->
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Bekleyen Kiralama Film  Durumu</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>

                            <th>Sipariş Numarası</th>
                            <th>Sipariş tarihi</th>
                            <th>Sipariş durumu</th>
                            <th>Toplam (₺)</th>



                            <th></th>


                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.OrderNumber
                                </td>
                                <td>
                                    @item.OrderDate
                                </td>
                                <td>
                                    @item.OrderState
                                </td>
                                <td>
                                    @item.Total
                                </td>


                                <td>
                                    <a class="btn btn-primary btn-sm" href="@Url.Action("Details",new { id = item.Id } )"><i class="fa fa-fw fa-edit"></i>Detay</a>


                                </td>
                            </tr>
                        }


                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>

                            <th>Sipariş Numarası</th>
                            <th>Sipariş tarihi</th>
                            <th>Sipariş durumu</th>
                            <th>Toplam (₺)</th>



                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>

Site/Views/Order1/Details.cshtml
@using Site.Models
@model OrderDetails1
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<section class="content">
    <div>

        <h4>Kiralama Bilgieri</h4>
        <hr />
        <div class="row">
            @if (TempData["mesaj"] != null)
            {
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4>	<i class="icon fa fa-check"></i> BAŞARILI!</h4>
                   Kiralama durumu Kaydedildi
                </div>
            }
        </div>
        <dl class="dl-horizontal">
            <dt>
                Kiralama Durumu :
            </dt>


            <dd>
                @using (Html.BeginForm("UpdateOrderState", "Order1", FormMethod.Post))
                {


                    @Html.HiddenFor(i => i.OrderId)
                    @Html.EnumDropDownListFor(i => i.OrderState, "Kiralama Durumu seç", new { @class = "form-control" })
                    <button type="submit" class="btn btn-primary">Güncelle</button>}
            </dd>

           
            
           
            <dt>
              Posta Kodu
            </dt>


            <dd>
                @Html.DisplayFor(Model => Model.PostaKodu)
            </dd>
            <dt>
                Adres
            </dt>


            <dd>
                Adres Başlığı:@Html.DisplayFor(Model => Model.Adres)
                <br />
                Adres :   @Html.DisplayFor(Model => Model.Adres)
                <br />
                Mahalle  @Html.DisplayFor(Model => Model.Mahalle)
                <br />
                İlçe  @Html.DisplayFor(Model => Model.Semt)
                <br />
                Şehir   @Html.DisplayFor(Model => Model.Sehir)
                <br />

            </dd>
        </dl>
    </div>



    <table class="table table-bordered table-condensed">
        <thead>
            <tr>
                <th>Resim</th>
                <th>Film Adı  </th>
                <th>Kiralama tutarı(₺) </th>
                <th>Adet</th>

                <th></th>
            </tr>
        </thead>


        <tbody>
            @foreach (var item in Model.OrderLines1)
            {
                <tr>
                    <td><img src="~/Content/image/@item.RESIM" height="75" width="75" /></td>
                    <td>@item.ProductName</td>
                    <td>
                        @if (item.FIYAT <= 0)
                        {
                            <label class="label label-danger"><i class="fa fa-fw fa-check-circle-o"></i>Stokta Yok</label>
                        }
                        else
                        {
                            <label class="label label-success"><i class="fa fa-fw fa-times-circle"></i>Stokta Var</label>
                        }
                    </td>
                    <td>@item.Quantity</td>
                    <td><a href="/Home/ProductDetails/@item.ProductId" class="btn btn-success" target="_blank">Ürün Detay </a></td>
                </tr>
            }

        </tbody>

    </table>
</section>

Site/Views/Order1/Index.cshtml
@using Site.Models
@model IEnumerable<AdminOrder1>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">

        <!-- /.box -->
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"> Kiralama Listesi</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>

                            <th>Kiralama Numarası</th>
                            <th>Kiralama tarihi</th>
                            <th>Kiralama durumu</th>
                            <th>Toplam (₺)</th>
                            <th>Film sayısı</th>


                            <th></th>


                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.OrderNumber
                                </td>
                                <td>
                                    @item.OrderDate
                                </td>
                                <td>
                                    @item.OrderState
                                </td>
                                <td>
                                    @item.Total
                                </td>
                                <td>
                                    @item.Count
                                </td>

                                <td>
                                    <a class="btn btn-primary btn-sm" href="@Url.Action("Details",new { id = item.Id } )"><i class="fa fa-fw fa-edit"></i>Kiralama Detay</a>


                                </td>
                            </tr>
                        }


                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>

                            <th>Sipariş Numarası</th>
                            <th>Sipariş tarihi</th>
                            <th>Sipariş durumu</th>
                            <th>Toplam (₺)</th>
                            <th>Ürün sayısı</th>


                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>

Site/Views/Order1/KargolananKiralamalar.cshtml
@using Site.Entity
@model IEnumerable<order1>
@{
    ViewBag.Title = "KargolananKiralamalar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">

        <!-- /.box -->
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"> Kargolanan Sipariş Durumu</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>

                            <th>Sipariş Numarası</th>
                            <th>Sipariş tarihi</th>
                            <th>Sipariş durumu</th>
                            <th>Toplam (₺)</th>



                            <th></th>


                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.OrderNumber
                                </td>
                                <td>
                                    @item.OrderDate
                                </td>
                                <td>
                                    @item.OrderState
                                </td>
                                <td>
                                    @item.Total
                                </td>


                                <td>
                                    <a class="btn btn-primary btn-sm" href="@Url.Action("Details",new { id = item.Id } )"><i class="fa fa-fw fa-edit"></i>Detay</a>


                                </td>
                            </tr>
                        }


                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>

                            <th>Sipariş Numarası</th>
                            <th>Sipariş tarihi</th>
                            <th>Sipariş durumu</th>
                            <th>Toplam (₺)</th>



                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>

Site/Views/Order1/PaketlenenKiralamalar.cshtml
@using Site.Entity
@model IEnumerable<order1>
@{
    ViewBag.Title = "PaketlenenKiralamalar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">

        <!-- /.box -->
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"> Paketlenen Sipariş Durumu</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>

                            <th>Sipariş Numarası</th>
                            <th>Sipariş tarihi</th>
                            <th>Sipariş durumu</th>
                            <th>Toplam (₺)</th>



                            <th></th>


                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.OrderNumber
                                </td>
                                <td>
                                    @item.OrderDate
                                </td>
                                <td>
                                    @item.OrderState
                                </td>
                                <td>
                                    @item.Total
                                </td>


                                <td>
                                    <a class="btn btn-primary btn-sm" href="@Url.Action("Details",new { id = item.Id } )"><i class="fa fa-fw fa-edit"></i>Detay</a>


                                </td>
                            </tr>
                        }


                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>

                            <th>Sipariş Numarası</th>
                            <th>Sipariş tarihi</th>
                            <th>Sipariş durumu</th>
                            <th>Toplam (₺)</th>



                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>

Site/Views/Order1/TamamlananKiralamalar.cshtml
@using Site.Entity
@model IEnumerable<order1>
@{
    ViewBag.Title = "TamamlananKiralamalar";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-xs-12">

        <!-- /.box -->
        <div class="box">
            <div class="box-header">
                <h3 class="box-title"> Tamamlanan Sipariş Durumu</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">

                <table id="example1" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>

                            <th>Sipariş Numarası</th>
                            <th>Sipariş tarihi</th>
                            <th>Sipariş durumu</th>
                            <th>Toplam (₺)</th>



                            <th></th>


                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>
                                    @item.OrderNumber
                                </td>
                                <td>
                                    @item.OrderDate
                                </td>
                                <td>
                                    @item.OrderState
                                </td>
                                <td>
                                    @item.Total
                                </td>


                                <td>
                                    <a class="btn btn-primary btn-sm" href="@Url.Action("Details",new { id = item.Id } )"><i class="fa fa-fw fa-edit"></i>Detay</a>


                                </td>
                            </tr>
                        }


                    </tbody>
                    <tfoot>
                        <tr>
                            <th>ID</th>

                            <th>Sipariş Numarası</th>
                            <th>Sipariş tarihi</th>
                            <th>Sipariş durumu</th>
                            <th>Toplam (₺)</th>



                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col -->
</div>